In [2]:
import pandas as pd
print("Pandas imported successfully")

Pandas imported successfully

In [3]:
# Loading the Dataset

In [3]:
df = pd.read_csv("Salaries.csv")
print("Dataset loaded successfully")

Dataset loaded successfully

Initial Inspection

In [6]:
df.head()

   Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
0           1      Prof          B           19.0         18.0  Male  139750
1           2      Prof          B           20.0         16.0  Male  173200
2           3  AsstProf          B            4.0          3.0  Male   79750
3           4      Prof          B           45.0         39.0  Male  115000
4           5      Prof          B           40.0         41.0  Male  141500

In [7]:
df.tail()

     Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
395         396      Prof          A           33.0         30.0  Male  103106
396         397      Prof          A           31.0         19.0  Male  150564
397         398      Prof          A           42.0         25.0  Male  101738
398         399      Prof          A           25.0         15.0  Male   95329
399         400  AsstProf          A            8.0          4.0  Male   81035

In [8]:
df.head(10)

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
0,1,Prof,B,19.0,18.0,Male,139750
1,2,Prof,B,20.0,16.0,Male,173200
2,3,AsstProf,B,4.0,3.0,Male,79750
3,4,Prof,B,45.0,39.0,Male,115000
4,5,Prof,B,40.0,41.0,Male,141500
5,6,AssocProf,B,6.0,6.0,Male,97000
6,7,Prof,B,30.0,23.0,NaN,175000
7,8,Prof,B,45.0,45.0,Male,147765
8,9,Prof,B,21.0,20.0,Male,119250
9,10,Prof,B,18.0,18.0,Female,129000

In [9]:
df.shape

(400, 7)

In [10]:
df.columns

Index(['Unnamed: 0', 'rank', 'discipline', 'yrs.since.phd', 'yrs.service',
       'sex', 'salary'],
      dtype='object')

In [11]:
df.dtypes

Unnamed: 0         int64
rank              object
discipline        object
yrs.since.phd    float64
yrs.service      float64
sex               object
salary             int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     400 non-null    int64
 1   rank           398 non-null    object
 2   discipline     400 non-null    object
 3   yrs.since.phd  399 non-null    float64
 4   yrs.service    399 non-null    float64
 5   sex            399 non-null    object
 6   salary         400 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 22.0+ KB

In [13]:
# Statistical summary of all columns
df.describe(include="all")

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
count,400.000000,398,400,399.000000,399.000000,399,400.000000
unique,NaN,3,2,NaN,NaN,2,NaN
top,NaN,Prof,B,NaN,NaN,Male,NaN
freq,NaN,267,219,NaN,NaN,360,NaN
mean,200.500000,NaN,NaN,22.338346,17.676692,NaN,113691.505000
std,115.614301,NaN,NaN,12.927059,13.039878,NaN,30260.734519
min,1.000000,NaN,NaN,1.000000,0.000000,NaN,57800.000000
25%,100.750000,NaN,NaN,12.000000,7.000000,NaN,91000.000000
50%,200.500000,NaN,NaN,21.000000,16.000000,NaN,107250.000000
75%,300.250000,NaN,NaN,32.000000,27.000000,NaN,134276.250000
max,400.000000,NaN,NaN,56.000000,60.000000,NaN,231545.000000

# Row Retrieval

In [15]:
# Retrieve first row using iloc
df.iloc[0]

Unnamed: 0            1
rank               Prof
discipline            B
yrs.since.phd      19.0
yrs.service        18.0
sex                Male
salary           139750
Name: 0, dtype: object

In [17]:
# Retrieve third row
df.iloc[2]

Unnamed: 0              3
rank             AsstProf
discipline              B
yrs.since.phd         4.0
yrs.service           3.0
sex                  Male
salary              79750
Name: 2, dtype: object

In [18]:
# Retrieve multiple rows: example rows 11 to 15
df.iloc[11: 16]

    Unnamed: 0      rank discipline  yrs.since.phd  yrs.service   sex  salary
11          12  AsstProf          B            7.0          2.0  Male   79800
12          13       NaN          B            1.0          NaN  Male   77700
13          14  AsstProf          B            2.0          0.0  Male   78000
14          15       NaN          B            NaN         18.0  Male  104800
15          16      Prof          B           45.0         45.0  Male  147765

# Column Retrival

In [4]:
# Retreive one column by column heading
df["salary"]

0      139750
1      173200
2       79750
3      115000
4      141500
        ...
395    103106
396    150564
397    101738
398     95329
399     81035
Name: salary, Length: 400, dtype: int64

In [5]:
# Retreive multiple columns by column heading
df[["rank", "salary"]]

         rank  salary
0        Prof  139750
1        Prof  173200
2    AsstProf   79750
3        Prof  115000
4        Prof  141500
..        ...     ...
395      Prof  103106
396      Prof  150564
397      Prof  101738
398      Prof   95329
399  AsstProf   81035

[400 rows x 2 columns]

In [7]:
# Retreive columns by column position
df.iloc[:, 1:4]

         rank discipline  yrs.since.phd
0        Prof          B           19.0
1        Prof          B           20.0
2    AsstProf          B            4.0
3        Prof          B           45.0
4        Prof          B           40.0
..        ...        ...            ...
395      Prof          A           33.0
396      Prof          A           31.0
397      Prof          A           42.0
398      Prof          A           25.0
399  AsstProf          A            8.0

[400 rows x 3 columns]

In [8]:
df.iloc[:,[1,4,5]]

         rank  yrs.service   sex
0        Prof         18.0  Male
1        Prof         16.0  Male
2    AsstProf          3.0  Male
3        Prof         39.0  Male
4        Prof         41.0  Male
..        ...          ...   ...
395      Prof         30.0  Male
396      Prof         19.0  Male
397      Prof         25.0  Male
398      Prof         15.0  Male
399  AsstProf          4.0  Male

[400 rows x 3 columns]

# Adding a New Row

In [9]:
new_row = {
    "rank": "AsstProf",
    "discipline": "A",
    "yrs.science.phd": 8,
    "yrs.service": 5,
    "sex": "Female",
    "salary": 85000,
}

In [10]:
# Add new row using loc
df.loc[len(df)] = new_row

In [11]:
df.tail()

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary
396,397.0,Prof,A,31.0,19.0,Male,150564
397,398.0,Prof,A,42.0,25.0,Male,101738
398,399.0,Prof,A,25.0,15.0,Male,95329
399,400.0,AsstProf,A,8.0,4.0,Male,81035
400,NaN,AsstProf,A,NaN,5.0,Female,85000

In [12]:
### Adding a new column
df["salary_in_lakhs"] = df["salary"] / 100000

In [13]:
df.head()

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,Prof,B,19.0,18.0,Male,139750,1.3975
1,2.0,Prof,B,20.0,16.0,Male,173200,1.7320
2,3.0,AsstProf,B,4.0,3.0,Male,79750,0.7975
3,4.0,Prof,B,45.0,39.0,Male,115000,1.1500
4,5.0,Prof,B,40.0,41.0,Male,141500,1.4150

# Subsetting

In [14]:
# Select first 10 rows and first 4 columns
s1 = df.iloc[0:10, 0:4]
s1.head()

   Unnamed: 0      rank discipline  yrs.since.phd
0         1.0      Prof          B           19.0
1         2.0      Prof          B           20.0
2         3.0  AsstProf          B            4.0
3         4.0      Prof          B           45.0
4         5.0      Prof          B           40.0

In [15]:
# Select only selectedd columns
s2 = df[["rank", "sex", "salary"]]
s2.head()

       rank   sex  salary
0      Prof  Male  139750
1      Prof  Male  173200
2  AsstProf  Male   79750
3      Prof  Male  115000
4      Prof  Male  141500

In [17]:
# Select rows 5 to 10 with selected columns
df.loc[5:10, ["rank", "yrs.service", "salary"]]

         rank  yrs.service  salary
5   AssocProf          6.0   97000
6        Prof         23.0  175000
7        Prof         45.0  147765
8        Prof         20.0  119250
9        Prof         18.0  129000
10  AssocProf          8.0  119800

# Filtering

In [18]:
# Filter employees with salary greater than 120000 (Handling numericsl column)
high_salary = df[df["salary"] > 120000]
high_salary

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,Prof,B,19.0,18.0,Male,139750,1.39750
1,2.0,Prof,B,20.0,16.0,Male,173200,1.73200
4,5.0,Prof,B,40.0,41.0,Male,141500,1.41500
6,7.0,Prof,B,30.0,23.0,NaN,175000,1.75000
7,8.0,Prof,B,45.0,45.0,Male,147765,1.47765
...,...,...,...,...,...,...,...,...
389,390.0,Prof,A,29.0,27.0,Male,139219,1.39219
392,393.0,Prof,A,33.0,18.0,Male,186023,1.86023
393,394.0,Prof,A,40.0,19.0,Male,166605,1.66605
394,395.0,Prof,A,30.0,19.0,Male,151292,1.51292
396,397.0,Prof,A,31.0,19.0,Male,150564,1.50564

In [19]:
prof = df[df["rank"] == "Prof"]
prof

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,Prof,B,19.0,18.0,Male,139750,1.39750
1,2.0,Prof,B,20.0,16.0,Male,173200,1.73200
3,4.0,Prof,B,45.0,39.0,Male,115000,1.15000
4,5.0,Prof,B,40.0,41.0,Male,141500,1.41500
6,7.0,Prof,B,30.0,23.0,NaN,175000,1.75000
...,...,...,...,...,...,...,...,...
394,395.0,Prof,A,30.0,19.0,Male,151292,1.51292
395,396.0,Prof,A,33.0,30.0,Male,103106,1.03106
396,397.0,Prof,A,31.0,19.0,Male,150564,1.50564
397,398.0,Prof,A,42.0,25.0,Male,101738,1.01738
398,399.0,Prof,A,25.0,15.0,Male,95329,0.95329

In [20]:
# Multiple conditions
filtered_data = df[(df["rank"] == "Prof") & (df["salary"] > 130000)]
filtered_data

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
0,1.0,Prof,B,19.0,18.0,Male,139750,1.39750
1,2.0,Prof,B,20.0,16.0,Male,173200,1.73200
4,5.0,Prof,B,40.0,41.0,Male,141500,1.41500
6,7.0,Prof,B,30.0,23.0,NaN,175000,1.75000
7,8.0,Prof,B,45.0,45.0,Male,147765,1.47765
...,...,...,...,...,...,...,...,...
389,390.0,Prof,A,29.0,27.0,Male,139219,1.39219
392,393.0,Prof,A,33.0,18.0,Male,186023,1.86023
393,394.0,Prof,A,40.0,19.0,Male,166605,1.66605
394,395.0,Prof,A,30.0,19.0,Male,151292,1.51292
396,397.0,Prof,A,31.0,19.0,Male,150564,1.50564

# Sorting

In [21]:
# Sort ascending
df.sort_values(by = "salary")

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
285,286.0,Prof,A,51.0,51.0,Male,57800,0.57800
126,127.0,AssocProf,A,25.0,22.0,Female,62884,0.62884
240,241.0,AsstProf,A,7.0,6.0,Female,63100,0.63100
229,230.0,AsstProf,A,3.0,1.0,Male,63900,0.63900
320,321.0,Prof,B,46.0,45.0,Male,67559,0.67559
...,...,...,...,...,...,...,...,...
80,81.0,Prof,B,26.0,19.0,Male,193000,1.93000
274,275.0,Prof,A,42.0,18.0,Male,194800,1.94800
252,253.0,Prof,A,29.0,7.0,Male,204000,2.04000
367,368.0,Prof,A,43.0,43.0,Male,205500,2.05500
44,45.0,Prof,B,38.0,38.0,Male,231545,2.31545

In [22]:
# Sort Descending
df.sort_values(by= "salary", ascending=False)

,Unnamed: 0,rank,discipline,yrs.since.phd,yrs.service,sex,salary,salary_in_lakhs
44,45.0,Prof,B,38.0,38.0,Male,231545,2.31545
367,368.0,Prof,A,43.0,43.0,Male,205500,2.05500
252,253.0,Prof,A,29.0,7.0,Male,204000,2.04000
274,275.0,Prof,A,42.0,18.0,Male,194800,1.94800
80,81.0,Prof,B,26.0,19.0,Male,193000,1.93000
...,...,...,...,...,...,...,...,...
320,321.0,Prof,B,46.0,45.0,Male,67559,0.67559
229,230.0,AsstProf,A,3.0,1.0,Male,63900,0.63900
240,241.0,AsstProf,A,7.0,6.0,Female,63100,0.63100
126,127.0,AssocProf,A,25.0,22.0,Female,62884,0.62884
285,286.0,Prof,A,51.0,51.0,Male,57800,0.57800

# Basic Aggregate Functions

In [24]:
# Mean
df["salary"].mean()

np.float64(113619.95511221945)

In [25]:
# Round
df["salary"].mean().round(2)

np.float64(113619.96)

In [26]:
# Max
df["salary"].max()

231545

In [27]:
# Min
df["salary"].min()

57800

In [31]:
# Unique
df["sex"].unique()

array(['Male', nan, 'Female'], dtype=object)

In [32]:
# Frequency
df["sex"].value_counts()

sex
Male      360
Female     40
Name: count, dtype: int64

# Saving the Dataset

In [33]:
df.to_csv("Salaries_updated.csv", index=False)